require('dual_caps')
require('watcher')
require('caffeinate')
require('window_movements')
require('app_hotkeys')
require('open_url')
require('window_focus')
require('insert_date')
hs.loadSpoon("PopupTranslateSelection")

hs.alert.show("Config loaded")
